# ---
# Welcome to LYDDE Group Jekyll Theme!
# Version : 1.0.0
# ---
# This site is a bootstrap 5.3 theme for Jekyll engine
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

#
# Build settings
#
remote_theme: jekyll-theme-lydde

#
# Site
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#
title: LYDDE # Your website title must be less than 50 char for SEO
description: >- # this means to ignore newlines until next entree
  We are a digital consulting company that helps businesses transform and thrive in the digital age. 
  We offer strategic advice, innovative solutions and expert guidance to help you achieve your goals and overcome your challenges.

#
# Brand
#
logo: "/assets/logo.png"
favicon: "assets/icons/favicon.ico"
tagline: Business and Tech Consulting

#
# Localization
#
timezone: Europe/Paris
language: en
locale: en_US

#
# Hosting
#
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /news/:categories/:title # the subpath of your posts, e.g. /news

#
# Collections
#
collections:
  categories:
    output: true
    
#
# Defaults values
#
defaults:
# all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/images/post.jpeg
      author: author-1
# all pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: /assets/images/page.jpeg

#
# Plugins used
#
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-feed  
  - jekyll-mentions
  - jekyll-redirect-from

#
# Plugin settings
#
relative_links:
  collections: true

#
# Files excluded
#
exclude:
  - readme.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/