#
# Welcome to LYDDE Group Website system
# Version : 1.0.0
#
# This site is a bootstrap 5.3 theme for Jekyll engine
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

#
# Theme
#
# Theme can be used from GEM Package or from GitHub Repos
# Default and recommanded usage is to rely on GitHub, to get latest version, even unpublished on GEM
# If you rely on GEM, uncomment theme and comment remote_theme
#
remote_theme: lydde/jekyll-lydde-theme

#
# Localization
#
# These are used to assist search engine and browser exposing the right language to user.
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
#
language: en # The language of the webpage
locale: en_US # The language of the webpage
timezone: Europe/Paris # Your website timezone

#
# Hosting
#
url: "https://lydde.com" # the base hostname & protocol for your site, e.g. https://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /news/:categories/:title # the subpath of your posts, e.g. /news

# 
# Site
# 
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#
title: LYDDE # Your website title (must be less than 50 char for SEO)
tagline: Business and Tech Consulting # Used in Title (should be limited to 50 char for SEO)
description: >- # used by SEO meta description and in feed.xml
  We are a digital consulting company that helps businesses transform and thrive in the digital age. 
  We offer strategic advice, innovative solutions and expert guidance to help you achieve your goals and overcome your challenges.

#
# Brand
#
# These are used to marketize your brand. If you look in the HTML files,
# you will see them in the header and the NavMenu.
#
logo: "/assets/logo.png" # if not set, default theme logo will be applied
favicon: "assets/icons/favicon.ico" # if not set, default theme icon will be applied

#
# Collections
#
collections:
    
#
# Defaults values
#
defaults:
# all posts
  - scope:
      path: "_posts" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      image: /assets/images/post.jpeg
      author: default
# all pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: /assets/images/page.jpeg
      
#
# Plugins
#
plugins:
  - jekyll-relative-links   #https://github.com/benbalter/jekyll-relative-links
  - jekyll-redirect-from    #https://github.com/jekyll/jekyll-redirect-from
  - jekyll-remote-theme     #https://github.com/benbalter/jekyll-remote-theme

#
# Plugin settings
#
relative_links:
  enabled:     true
  collections: true

compress_html: # Details on https://jch.penibelst.de/
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
    
#
# Files excluded
#
exclude:
  - readme.md
  - LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - "*.gem"
  - "*.gemspec"
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/