# ---
# Welcome to LYDDE Group Jekyll!
# Version : 1.0.0
# ---
# This site is a bootstrap 5.3 theme for Jekyll engine
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
# Others settings are in /_settings/
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#

#
# Build settings
#
theme: jekyll-theme-lydde

# 
# Site settings
# 
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#
title: LYDDE
email: your-email@example.com
tagline: Game developer unleashed 
logo: "/assets/logo.png"
favicon: "assets/icons/favicon.ico"
language: en
locale: en_US
description: >- # this means to ignore newlines until "timezone:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
timezone: Europe/Paris

#
# Hosting Settings
#
permalink: /:title
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#
# Plugins used
#
plugins:
  - jekyll-feed

#
# Plugin settings
#
relative_links:
  collections: true

#
# Files excluded
#
exclude:
  - readme.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/